services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    container_name: notification_app
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
    env_file:
      - ../.env
    depends_on:
      - rabbitmq

  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile.worker
    container_name: notification_worker
    volumes:
      - ..:/app
    env_file:
      - ../.env
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always
